# Generated by Django 2.2.4 on 2019-08-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
